#!/usr/bin/env bash
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"

# Allow the release name to be provided
release_name="${1}"
if [ -z "${release_name}" ]; then
    release_name="${tag}"
fi

# Start by building the gem
gem build ./*.gemspec ||
    failure "Unable to build RubyGem"

gem_files=(./*.gem)
if [ ! -f "${gem_files[0]}" ]; then
    failure "Could not find built RubyGem"
fi
gem_file="${gem_files[0]}"

# Create the GitHub release
release "${release_name}" "${gem_file}"
