on:
  push:
    tags: 'v*'

jobs:
  github-release:
    if: github.repository == 'hashicorp/ruby-checkpoint'
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions:
      content: write
    uses: ./.github/workflows/github-release.yml
  publish-rubygem:
    if: github.repository == 'hashicorp/ruby-checkpoint'
    needs: [github-release]
    name: Trigger RubyGem publication
    runs-on: ubuntu-latest
    uses: ./.github/workflows/publish-rubygem.yml
    secrets: inherit
