on:
  push:
    tags: 'v*'
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the GitHub release (example: v1.0.0)'
        type: string
        require: true

jobs:
  github-release:
    if: github.repository == 'hashicorp/ruby-checkpoint'
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions:
      content: write
    uses: ./.github/workflows/github-release.yml
    with:
      release_name: ${{ inputs.release_name }}
  publish-rubygem:
    if: github.repository == 'hashicorp/ruby-checkpoint'
    needs: [github-release]
    name: Trigger RubyGem publication
    runs-on: ubuntu-latest
    uses: ./.github/workflows/publish-rubygem.yml
    secrets: inherit
    with:
      release_name: ${{ inputs.release_name }}
