name: Vagrant Ruby Tests
on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'lib/**'
      - 'spec/**'
      - 'Gemfile'
      - 'ruby-checkpoint.gemspec'
      - 'Rakefile'
  pull_request:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'spec/**'
      - 'Gemfile'
      - 'ruby-checkpoint.gemspec'
      - 'Rakefile'

jobs:
  unit-tests-ruby:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        ruby: [ '3.1', '3.2', '3.3', '3.4' ]
    name: Vagrant unit tests on Ruby ${{ matrix.ruby }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@922ebc4c5262cd14e07bb0e1db020984b6c064fe # v1.226.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rspec
